backend = "glx";
vsync = true;
use-damage = true;

corner-radius = 4;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Polybar'"
];

fading = true;
fade-delta = 10;
fade-in-step = 0.08;
fade-out-step = 0.08;

detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
unredir-if-possible = true;
use-ewmh-active-win = true;

experimental-backends = true;
focus-exclude = [ "class_g = 'Polybar'" ];

# blur:
# {
#   method = "box";
#   size = 0;
#   background = false;
#   background-frame = false;
#   background-fixed = false;
# };

blur-background-exclude = [
  "class_g != 'Alacritty'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'notification'"
];

