general.import = [
  "~/.config/alacritty/ayu.toml"
]

[window]
decorations = "full"
startup_mode = "Windowed"
opacity = 0.85

[font]
size = 8

[font.normal]
family = "Monaspace Argon NF"

[selection]
save_to_clipboard = true
