general.import = [
  "~/.config/alacritty/ayu.toml"
]

[window]
decorations = "full"
startup_mode = "Windowed"

[font]
size = 9.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[selection]
save_to_clipboard = true

