general.import = [
  "~/.config/alacritty/ayu.toml"
]

[window]
decorations = "full"
startup_mode = "Windowed"
opacity = 0.9

[font]
size = 9

[font.normal]
family = "UbuntuMono Nerd Font"

[selection]
save_to_clipboard = true

