general.import = [
  "~/.config/alacritty/ayu.toml"
]

[window]
decorations = "full"
startup_mode = "Windowed"
# opacity = 0.991

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[selection]
save_to_clipboard = true

