gesture: swipe left 3   xdotool key super+Left
gesture: swipe right 3  xdotool key super+Right
gesture: swipe up 3     xdotool key super+Up
gesture: swipe down 3    xdotool key super+Down

gesture: pinch out 2    xdotool key ctrl+equal
gesture: pinch in 2     xdotool key ctrl+minus

