-- Generated by nwg-displays on 2026-08-22 at 16:43:25. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@120.0",
    position = "0x559",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0
})
